### ISSUE TITLE
Add the ‘hacktoberfest’ topic to the repository

### ISSUE THREAD

**Issue by rogdex24** [VIPverma01/AmongCode#24]
Hacktoberfest has added a new update , due to spammy PR's going on a huge number . 

[https://hacktoberfest.digitalocean.com/hacktoberfest-update](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

For the PR's to be valid for the hacktoberfest they need to merged or added the label : accepted for hacktoberfest 

Please Look into this @VIPverma01

**Comment by VIPverma01** [comment]
Yes I have done @Abu-Talha-24
